language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get -y install xorg-dev
  - sudo apt-get -y install libsdl2-dev libsdl2-image-dev
