[package]
name = "rustboyadvance-ng"
version = "0.1.0"
authors = ["Michel Heily <michelheily@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
num = "0.2.0"
num-traits = "0.2"
enum-primitive-derive = "^0.1"
bit = "^0.1"
clap = {version = "2.33", features = ["color", "yaml"]}
rustyline = "5.0.0"
nom = "5.0.0"
colored = "1.8"
ansi_term = "0.11.0"
hexdump = "0.1.0"
sdl2 = "0.32.2"
minifb = "0.11.2"
time = "0.1.42"
bitfield = "0.13.1"
bitflags = "1.1.0"
zip = "0.5.3"
ctrlc = "3.1.3"
cpal="0.10.0"

[[bin]]
name = "rba-sdl2"
path = "src/plat/sdl2/main.rs"

[[bin]]
name = "rba-minifb"
path = "src/plat/minifb/main.rs"


[profile.dev]
opt-level = 0
debug = true